export default {
  movies: [
    {
      adult: false,
      backdrop_path: "/crnno9YoWMkPUEim5JdLDCKsKk5.jpg",
      genre_ids: [10770, 12, 878],
      id: 15691,
      original_language: "en",
      original_title: "Doctor Who",
      overview:
        "The Seventh Doctor becomes the Eighth. And on the streets of San Francisco – alongside new ally Grace Holloway - he battles the Master.",
      popularity: 6.704,
      poster_path: "/ytgbAsMprSRhpoVGHHYWlxc0lcy.jpg",
      release_date: "1996-05-12",
      title: "Doctor Who",
      video: false,
      vote_average: 6.2,
      vote_count: 172,
    },
    {
      adult: false,
      backdrop_path: "/po29ds1hY35mSBkK2gpTNUZDsW.jpg",
      genre_ids: [878, 12],
      id: 313106,
      original_language: "en",
      original_title: "Doctor Who: The Day of the Doctor",
      overview:
        "In 2013, something terrible is awakening in London's National Gallery; in 1562, a murderous plot is afoot in Elizabethan England; and somewhere in space an ancient battle reaches its devastating conclusion. All of reality is at stake as the Doctor's own dangerous past comes back to haunt him.",
      popularity: 17.927,
      poster_path: "/qkhP3bhxQQjs1bGEWNts64DOUkK.jpg",
      release_date: "2013-11-23",
      title: "Doctor Who: The Day of the Doctor",
      video: false,
      vote_average: 8.2,
      vote_count: 649,
    },
    {
      adult: false,
      backdrop_path: "/qXRlEHW05mdOQLnudLkCUyrZX97.jpg",
      genre_ids: [18, 878, 10770],
      id: 282848,
      original_language: "en",
      original_title: "Doctor Who: The Time of the Doctor",
      overview:
        "Orbiting a quiet backwater planet, the massed forces of the universe's deadliest species gather, drawn to a mysterious message that echoes out to the stars. And amongst them, the Doctor. Rescuing Clara from a family Christmas dinner, the Time Lord and his best friend must learn what this enigmatic signal means for his own fate and that of the universe.",
      popularity: 16.64,
      poster_path: "/7blrzLLfj34vV45HYmPccvhNSRZ.jpg",
      release_date: "2013-12-25",
      title: "Doctor Who: The Time of the Doctor",
      video: false,
      vote_average: 8.1,
      vote_count: 246,
    },
    {
      adult: false,
      backdrop_path: "/1qmefUkrzXW4XDKVtEGFFxHPBeI.jpg",
      genre_ids: [878],
      id: 315620,
      original_language: "en",
      original_title: "Doctor Who: A Christmas Carol",
      overview:
        "Amy Pond and Rory Williams are trapped on a crashing space liner, and the only way the Eleventh Doctor can rescue them is to save the soul of a lonely old miser. But is Kazran Sardick, the richest man in Sardicktown, beyond redemption? And what is lurking in the fogs of Christmas Eve?",
      popularity: 10.133,
      poster_path: "/hBcRd2e52ddwjjLzjxUJzdD4EEk.jpg",
      release_date: "2010-12-25",
      title: "Doctor Who: A Christmas Carol",
      video: false,
      vote_average: 8,
      vote_count: 191,
    },
    {
      adult: false,
      backdrop_path: "/eCTWG4HzsOQomghw8sRd1qpeOlA.jpg",
      genre_ids: [878],
      id: 282758,
      original_language: "en",
      original_title: "Doctor Who: The Runaway Bride",
      overview:
        "A young bride in the midst of her wedding finds herself mysteriously transported to the TARDIS. The Doctor must discover what her connection is with the Empress of the Racnoss's plan to destroy the world.",
      popularity: 9.011,
      poster_path: "/gkTCC4VLv8jATM3kouAUK3EaoGd.jpg",
      release_date: "2006-12-25",
      title: "Doctor Who: The Runaway Bride",
      video: false,
      vote_average: 7.8,
      vote_count: 194,
    },
    {
      adult: false,
      backdrop_path: "/szMyShEn7HYmYo2TMMuGrWxmhTG.jpg",
      genre_ids: [878, 12, 18],
      id: 317182,
      original_language: "en",
      original_title: "Doctor Who: Last Christmas",
      overview:
        "The Doctor and Clara face their Last Christmas. Trapped on an Arctic base, under attack from terrifying creatures, who are you going to call? Santa Claus!",
      popularity: 7.103,
      poster_path: "/tpvZ4LxqBLIacWBMJueXPIbdlwP.jpg",
      release_date: "2014-12-25",
      title: "Doctor Who: Last Christmas",
      video: false,
      vote_average: 7.8,
      vote_count: 205,
    },
    {
      adult: false,
      backdrop_path: "/8CEvvYU4XlN1mSiSPAgWiyfeyz4.jpg",
      genre_ids: [878, 12],
      id: 495151,
      original_language: "en",
      original_title: "Doctor Who: Twice Upon a Time",
      overview:
        "As the Twelfth Doctor nears regeneration, he stumbles on his first incarnation, also refusing to change. It takes a captain, a glass avatar and a familiar face to convince the Doctors the universe still needs them.",
      popularity: 10.615,
      poster_path: "/6QKNt1NtBeA2r9olsDyopgJbk2Q.jpg",
      release_date: "2017-12-25",
      title: "Doctor Who: Twice Upon a Time",
      video: false,
      vote_average: 8.1,
      vote_count: 99,
    },
    {
      adult: false,
      backdrop_path: "/lbjFL4zFzloqZPySgoIDuWgLzto.jpg",
      genre_ids: [878, 10770],
      id: 317190,
      original_language: "en",
      original_title: "Doctor Who: The Next Doctor",
      overview:
        "The Doctor arrives in Victorian London. It's Christmas, but snow isn't the only thing descending on the tranquil and jubilant civilization, as familiar silver giants from an alternate reality are amassing in numbers. The Cybermen are on the move again, and the only beings who can stop them are the Doctor and... another Doctor?",
      popularity: 7.703,
      poster_path: "/kDqIMVtDx9UuexVJVNXUxUrHfJl.jpg",
      release_date: "2008-12-25",
      title: "Doctor Who: The Next Doctor",
      video: false,
      vote_average: 7.4,
      vote_count: 180,
    },
    {
      adult: false,
      backdrop_path: "/nVn846U8YgDuh7QtRIv0iIKA0pq.jpg",
      genre_ids: [10770, 12, 878, 18, 10751],
      id: 369145,
      original_language: "en",
      original_title: "Doctor Who: The Snowmen",
      overview:
        "The Doctor has retired to 1892 London. Despite the protests of his allies, he is determined to keep out of mankind's affairs. However, a governess named Clara has stumbled upon a plot which only the Doctor can unravel, involving the death of her predecessor in ice and the sinister Dr. Simeon, who controls monsters made of sentient snow. And there is another mystery afoot: Clara is the spitting image of Oswin Oswald, whom the Doctor saw die in the Dalek asylum...",
      popularity: 5.384,
      poster_path: "/6JEGsCbGcNiF0WUyoqL0ACmAjFi.jpg",
      release_date: "2012-12-25",
      title: "Doctor Who: The Snowmen",
      video: false,
      vote_average: 7.8,
      vote_count: 185,
    },
    {
      adult: false,
      backdrop_path: "/boqvy9im9HTV3KfBWLio3oRl8qs.jpg",
      genre_ids: [878, 10770],
      id: 419786,
      original_language: "en",
      original_title: "Doctor Who: Time Crash",
      overview:
        "After Martha Jones parts company with the Doctor, his TARDIS collides with another, and he comes face to face with one of his previous incarnations.",
      popularity: 7.036,
      poster_path: "/ge7vWbyrQpsFwSGRED8p4xpi3kZ.jpg",
      release_date: "2007-11-16",
      title: "Doctor Who: Time Crash",
      video: false,
      vote_average: 7.8,
      vote_count: 79,
    },
    {
      adult: false,
      backdrop_path: "/uePRd8roqrTI6CUn934yEJfab0u.jpg",
      genre_ids: [10770, 878, 12, 18, 10751],
      id: 384257,
      original_language: "en",
      original_title: "Doctor Who: Deep Breath",
      overview:
        "The newly-regenerated Doctor arrives in Victorian London, and Clara Oswald struggles to embrace the man he has become. All the while, they reunite with the Paternoster Gang to investigate a series of combustions that have been occurring all around the city.",
      popularity: 5.506,
      poster_path: "/3lHjHwtZ3GOBqIvhf3pMJvVhZpy.jpg",
      release_date: "2014-08-23",
      title: "Doctor Who: Deep Breath",
      video: true,
      vote_average: 7.7,
      vote_count: 102,
    },
    {
      adult: false,
      backdrop_path: "/tBcpBqq1gOT7CZc4m7sj2KDy68m.jpg",
      genre_ids: [878, 18],
      id: 315623,
      original_language: "en",
      original_title: "Doctor Who: The Doctor, the Widow and the Wardrobe",
      overview:
        "It's Christmas Eve, 1938, when Madge Arwell comes to the aid of an injured Spaceman Angel as she cycles home. He promises to repay her kindness - all she has to do is make a wish.",
      popularity: 12.52,
      poster_path: "/3yJ2HKPsIXYhn8cqTClvvuoZyX7.jpg",
      release_date: "2011-12-25",
      title: "Doctor Who: The Doctor, the Widow and the Wardrobe",
      video: false,
      vote_average: 6.8,
      vote_count: 88,
    },
    {
      adult: false,
      backdrop_path: "/zjx8V9rTkJ1O6O1wpjTQ4NysRQS.jpg",
      genre_ids: [878, 10770],
      id: 281979,
      original_language: "en",
      original_title: "Doctor Who: The Waters of Mars",
      overview:
        "In a Mars base, the inhabitants are being infected by a mysterious water creature which takes over its victims. The Doctor is thrust into the middle of this catastrophe, knowing a larger one is waiting around the corner.",
      popularity: 6.533,
      poster_path: "/ikb6cZI8RXUqcxApMJmIdimAJ1X.jpg",
      release_date: "2009-11-15",
      title: "Doctor Who: The Waters of Mars",
      video: false,
      vote_average: 7.9,
      vote_count: 182,
    },
    {
      adult: false,
      backdrop_path: "/nW3fOT5T9HXqDG95ZD5PhNlDTln.jpg",
      genre_ids: [878, 12, 28, 18, 10770],
      id: 491940,
      original_language: "en",
      original_title: "Doctor Who: Shada",
      overview:
        "The story revolves around the lost planet Shada, on which the Time Lords built a prison for defeated would-be conquerors of the universe. Skagra, one such inmate, needs the help of one of the prison's inmates. He finds nobody knows where Shada is anymore except one aged Time Lord who has retired to Earth, where he is a professor at St. Cedd's College, Cambridge. Luckily for the universe, Skagra's attempt to force the information out of Professor Chronotis coincides with a visit by the professor's old friend, the Doctor. (Filming for this story was never finished, and in this version the story is completed via animation.)",
      popularity: 4.077,
      poster_path: "/fnynoiW4QUga1IlBcPAAR1I7N7h.jpg",
      release_date: "2017-11-24",
      title: "Doctor Who: Shada",
      video: true,
      vote_average: 7.5,
      vote_count: 12,
    },
    {
      adult: false,
      backdrop_path: "/wLc0dS39Xl8mPJqUKL5JBRhhYqc.jpg",
      genre_ids: [878, 10770],
      id: 335209,
      original_language: "en",
      original_title: "Doctor Who: Voyage of the Damned",
      overview:
        "When disaster hits the Titanic, the Doctor uncovers a threat to the whole human race. Battling alongside aliens, saboteurs, robot Angels and a new friend called Astrid, can he stop the Christmas inferno?",
      popularity: 6.502,
      poster_path: "/qav0QtsBKvcnpJHqFgFTjynkTca.jpg",
      release_date: "2007-12-25",
      title: "Doctor Who: Voyage of the Damned",
      video: false,
      vote_average: 7.6,
      vote_count: 160,
    },
    {
      adult: false,
      backdrop_path: "/oSCo4yTbr61VVs9T4XcQbYi96T6.jpg",
      genre_ids: [878, 10770],
      id: 282963,
      original_language: "en",
      original_title: "Doctor Who: Planet of the Dead",
      overview:
        "A meeting in a London bus with jewel thief Lady Christina takes a turn for the worse for the Doctor when the bus takes a detour to a desert-like planet, where the deadly Swarm awaits.",
      popularity: 6.355,
      poster_path: "/s8qWZKmi1ZloKhGXKMNMLPDHw7Q.jpg",
      release_date: "2009-04-11",
      title: "Doctor Who: Planet of the Dead",
      video: false,
      vote_average: 7.5,
      vote_count: 178,
    },
    {
      adult: false,
      backdrop_path: "/gXIcwtfL9vFdYDTNnoQLSzIYiOC.jpg",
      genre_ids: [18, 878, 35, 10770],
      id: 371759,
      original_language: "en",
      original_title: "Doctor Who: The Husbands of River Song",
      overview:
        "It’s Christmas Day on a remote human colony and the Doctor is hiding from Christmas Carols and Comedy Antlers. But when a crashed spaceship calls upon the Doctor for help, he finds himself recruited into River Song’s squad and hurled into a fast and frantic chase across the galaxy. King Hydroflax is furious, and his giant Robot bodyguard is out-of-control and coming for them all! Will Nardole survive? And when will River Song work out who the Doctor is? All will be revealed on a starliner full of galactic super-villains and a destination the Doctor has been avoiding for a very long time.",
      popularity: 6.539,
      poster_path: "/ettlSCoR5YhEoXx5b7JWwzstASz.jpg",
      release_date: "2015-12-25",
      title: "Doctor Who: The Husbands of River Song",
      video: false,
      vote_average: 8,
      vote_count: 134,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [878, 18, 12, 10770],
      id: 964096,
      original_language: "en",
      original_title: "Doctor Who: The Centenary Special",
      overview:
        "The Thirteenth Doctor faces the forces that mass against her in her final feature-length adventure.",
      popularity: 3.24,
      poster_path: null,
      release_date: "2022-10-23",
      title: "Doctor Who: The Centenary Special",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [12, 35, 878, 10770],
      id: 421142,
      original_language: "en",
      original_title: "Doctor Who: Space/Time",
      overview:
        "A special two-part mini episode where the Doctor, Amy, and Rory find themselves in trouble when the TARDIS materializes inside of itself.",
      popularity: 2.407,
      poster_path: null,
      release_date: "2011-03-18",
      title: "Doctor Who: Space/Time",
      video: false,
      vote_average: 7.5,
      vote_count: 34,
    },
    {
      adult: false,
      backdrop_path: "/qpsRCis9nkG3GnjaxYp9EZ0ix2e.jpg",
      genre_ids: [18, 12, 878, 10770, 28],
      id: 438053,
      original_language: "en",
      original_title: "Doctor Who: Castrovalva",
      overview:
        "The Doctor needs somewhere peaceful to recover from his traumatic regeneration. But the sanctuary of Castrovalva is not all it seems, as the Master will stop at nothing to gain his revenge over the Doctor...",
      popularity: 1.681,
      poster_path: "/hnsf1g86IeFrzEkpSeNsHD9PSPV.jpg",
      release_date: "1982-01-12",
      title: "Doctor Who: Castrovalva",
      video: true,
      vote_average: 8,
      vote_count: 3,
    },
  ],
  shows: [
    {
      backdrop_path: "/84XPpjGvxNyExjSuLQe0SzioErt.jpg",
      first_air_date: "2008-01-20",
      genre_ids: [18],
      id: 1396,
      name: "Breaking Bad",
      origin_country: ["US"],
      original_language: "en",
      original_name: "Breaking Bad",
      overview:
        "When Walter White, a New Mexico chemistry teacher, is diagnosed with Stage III cancer and given a prognosis of only two years left to live. He becomes filled with a sense of fearlessness and an unrelenting desire to secure his family's financial future at any cost as he enters the dangerous world of drugs and crime.",
      popularity: 342.983,
      poster_path: "/ggFHVNu6YYI5L9pCfOacjizRGt.jpg",
      vote_average: 8.8,
      vote_count: 8883,
    },
    {
      backdrop_path: "/9ayox8zhcllxKRjP3NA5KBp5M5v.jpg",
      first_air_date: "2011-04-06",
      genre_ids: [35, 10759, 18],
      id: 34541,
      name: "Breaking In",
      origin_country: ["US"],
      original_language: "en",
      original_name: "Breaking In",
      overview:
        "Contra Security is a high tech security firm that specializes in breaking in as a way to test security measures. The team members comprise various skills, and even more various personalities.",
      popularity: 10.351,
      poster_path: "/cDEglbhl4g6yFg203agZAOm8m3b.jpg",
      vote_average: 6.6,
      vote_count: 44,
    },
    {
      backdrop_path: "/gmekCcoKxkyDOPeWB7uY0kWCq8T.jpg",
      first_air_date: "2018-06-10",
      genre_ids: [99, 10764],
      id: 80106,
      name: "Breaking the Band",
      origin_country: ["US"],
      original_language: "en",
      original_name: "Breaking the Band",
      overview:
        "The battling egos, power struggles and inter-band rivalries that split up The Beatles, The Supremes, Fleetwood Mac, The Eagles, The Beach Boys, N.W.A, Van Halen and Sonny and Cher. From crippling drug addictions to scandalous affairs, we uncover the incredible true stories by recreating the key moments the cameras missed in addition to using rare band interviews and off-stage footage to piece together each dramatic tale.",
      popularity: 5.788,
      poster_path: "/g85G6qvMkfa6m7x0Uf4XOTRdyhH.jpg",
      vote_average: 6,
      vote_count: 1,
    },
    {
      backdrop_path: null,
      first_air_date: "2002-07-17",
      genre_ids: [18],
      id: 10728,
      name: "Breaking News",
      origin_country: ["US"],
      original_language: "en",
      original_name: "Breaking News",
      overview:
        "Breaking News is an American drama television series about the fictional Milwaukee-based 24-hour cable news television network I-24, with the motto 'Around the Clock, Around the World.' The series premiered July 17, 2002, on Bravo.",
      popularity: 4.214,
      poster_path: "/9JA2qZcOeOIjczg6ESyLE1of4bT.jpg",
      vote_average: 5,
      vote_count: 1,
    },
    {
      backdrop_path: null,
      first_air_date: "1963-09-16",
      genre_ids: [18],
      id: 16377,
      name: "Breaking Point",
      origin_country: ["US"],
      original_language: "en",
      original_name: "Breaking Point",
      overview:
        "Breaking Point is an American medical drama that aired on ABC from September 16, 1963, to April 27, 1964, continuing in rebroadcasts until September 7. The series, which was a spinoff of Ben Casey, stars Paul Richards and Eduard Franz. The series was created by Meta Rosenberg.",
      popularity: 4.126,
      poster_path: null,
      vote_average: 7.5,
      vote_count: 2,
    },
    {
      backdrop_path: "/n3H3BI6Nj9UvDD8WlL4RVZs9PfY.jpg",
      first_air_date: "2012-09-09",
      genre_ids: [99],
      id: 45754,
      name: "Breaking Amish",
      origin_country: ["US"],
      original_language: "en",
      original_name: "Breaking Amish",
      overview:
        "Temptations abound as a group of young Amish explore life beyond their Amish culture. Ultimately, they will make the biggest decision of their lives – to remain Amish/Mennonite or become English and face the consequences of being shunned by their family and friends.",
      popularity: 2.194,
      poster_path: "/74wVDELZwZAHLS5DAEuGItM82YX.jpg",
      vote_average: 5.9,
      vote_count: 11,
    },
    {
      backdrop_path: "/lMIw4oDMaTascHaYdklJA2dMbWW.jpg",
      first_air_date: "2019-01-02",
      genre_ids: [10764],
      id: 85466,
      name: "Bradley Walsh & Son: Breaking Dad",
      origin_country: ["GB"],
      original_language: "en",
      original_name: "Bradley Walsh & Son: Breaking Dad",
      overview:
        "Actor Bradley Walsh and his 20-year-old son Barney are hitting the road together, travelling over 2000 miles from Los Angeles to New Orleans.",
      popularity: 5.331,
      poster_path: "/5iAHSzXJAyR87OBZBU1TLvxWCO0.jpg",
      vote_average: 10,
      vote_count: 2,
    },
    {
      backdrop_path: null,
      first_air_date: "1980-11-29",
      genre_ids: [18],
      id: 21394,
      name: "Breaking Away",
      origin_country: ["US"],
      original_language: "en",
      original_name: "Breaking Away",
      overview:
        "Breaking Away is a 1980 American comedy-drama television series that was based on the 1979 film of the same name. It was created by Steve Tesich, who wrote the original film, and the film's director Peter Yates served as Executive Producer.\n\nAs a prequel, the series was set during the year prior to the events of the film. Shaun Cassidy took over the role of Dave Stohler, a young man mad about bicycle racing and all things Italian. Barbara Barrie, Jackie Earle Haley and John Ashton reprised their roles from the film. The television series was set in Bloomington, Indiana, but was actually shot in Athens, Georgia.\n\nThe show was caught up in the 1980 Screen Actors Guild Strike and did not begin production until that fall. While heavily promoted by ABC, it was overlooked by TV audiences once it got on the air and suffered low ratings. It was cancelled after eight episodes were filmed, though only seven episodes aired during its original run. ABC showed reruns of the show during the summer of 1981, and it was also rerun by the Arts & Entertainment cable channel during 1985–1987.",
      popularity: 2.132,
      poster_path: "/2JRJVesVyy5PG0cxTaqfPFER5jv.jpg",
      vote_average: 0,
      vote_count: 0,
    },
    {
      backdrop_path: "/lCi9poXSuzJMnPudXDSTrvH5u8E.jpg",
      first_air_date: "2008-10-02",
      genre_ids: [99],
      id: 6391,
      name: "Breaking the Magician's Code: Magic's Biggest Secrets Finally Revealed",
      origin_country: ["US"],
      original_language: "en",
      original_name:
        "Breaking the Magician's Code: Magic's Biggest Secrets Finally Revealed",
      overview:
        "The Masked Magician returns to television to defy his fellow conjurers and disclose the tricks that have captivated audiences for centuries. Nowhere else has a magician dared to expose the secrets behind the world's most mystifying illusions.",
      popularity: 10.431,
      poster_path: "/m6JNAfRYVaEtD03sJhqPlsqXW4o.jpg",
      vote_average: 7.6,
      vote_count: 123,
    },
    {
      backdrop_path: null,
      first_air_date: "1966-10-22",
      genre_ids: [],
      id: 27444,
      name: "Breaking Point (UK)",
      origin_country: ["GB"],
      original_language: "en",
      original_name: "Breaking Point (UK)",
      overview: "",
      popularity: 1.4,
      poster_path: null,
      vote_average: 0,
      vote_count: 0,
    },
    {
      backdrop_path: null,
      first_air_date: "2015-10-25",
      genre_ids: [],
      id: 64238,
      name: "WWE Breaking Ground",
      origin_country: [],
      original_language: "en",
      original_name: "WWE Breaking Ground",
      overview:
        "Narrated by legendary actor and voiceover artist William Shatner, Breaking Ground gives viewers access to the WWE Performance Center, chronicling what it takes to become a WWE Superstar.",
      popularity: 1.799,
      poster_path: "/iqeLMTxDhHECzrRilEZRMt6tkLy.jpg",
      vote_average: 6.3,
      vote_count: 3,
    },
    {
      backdrop_path: "/2MfilSH9DiTgCWCM08PGwoKP9xl.jpg",
      first_air_date: "2012-05-31",
      genre_ids: [10764],
      id: 43151,
      name: "Breaking Pointe",
      origin_country: ["US"],
      original_language: "en",
      original_name: "Breaking Pointe",
      overview:
        "Goes behind the stage curtain for an intense, unfiltered look at one of the most competitive ballet companies in the country, Ballet West, in Salt Lake City, Utah. Beneath the beauty and glamour of the dance and costumes is a gritty dog-eat-dog world of extreme athleticism, focus, dedication, passion, pressure and, of course, the hunt for the unattainable... perfection.",
      popularity: 1.282,
      poster_path: "/2bOwRDraB1m8SUEq6twgd8vYobk.jpg",
      vote_average: 6.5,
      vote_count: 3,
    },
    {
      backdrop_path: null,
      first_air_date: "",
      genre_ids: [],
      id: 20669,
      name: "Breaking Point",
      origin_country: [],
      original_language: "en",
      original_name: "Breaking Point",
      overview:
        "Breaking Point is a Canadian documentary film, released in 2005. Aired on CBC Television in English and on Télévision de Radio-Canada in French and released to mark the tenth anniversary of the 1995 Quebec sovereignty referendum, the film explored the dynamics of the referendum campaign through interviews with and news clips of several of the major players on both sides of the debate.\n\nThe two-part film aired on SRC in September 2005, and on CBC in October. It has also been released on DVD.",
      popularity: 0.6,
      poster_path: null,
      vote_average: 0,
      vote_count: 0,
    },
    {
      backdrop_path: "/eRJN9V7CRM68xtYGMHJgsDl4wkZ.jpg",
      first_air_date: "2021-05-31",
      genre_ids: [99],
      id: 118454,
      name: "Breaking Bobby Bones",
      origin_country: ["US"],
      original_language: "en",
      original_name: "Breaking Bobby Bones",
      overview:
        "Bobby Bones crisscrosses the country to meet everyday heroes who have extraordinary jobs, hobbies and abilities, welcoming him with open arms to give him a crash course in their specialized skills.",
      popularity: 1.243,
      poster_path: "/hukCREjIdma7dRQ9J0qbPRSb8eD.jpg",
      vote_average: 0,
      vote_count: 0,
    },
    {
      backdrop_path: null,
      first_air_date: "2015-01-29",
      genre_ids: [10764, 35],
      id: 61972,
      name: "Breaking Greenville",
      origin_country: ["US"],
      original_language: "en",
      original_name: "Breaking Greenville",
      overview:
        "Breaking Greenville takes viewers behind the cameras of two real-life rival TV news stations in one of the smallest TV markets in America: Greenville, Miss. The character-driven, comedic docu-soap spotlights the playful - and at times cut-throat - rivalry between two local news stations and the dynamic newscasters who are determined to take their jobs seriously, even when some of the news they cover is less than serious.",
      popularity: 0.846,
      poster_path: null,
      vote_average: 0,
      vote_count: 0,
    },
    {
      backdrop_path: "/bFdVXwUAG0WXzkweSIsjvmGQ0KR.jpg",
      first_air_date: "2018-04-15",
      genre_ids: [80, 99],
      id: 78821,
      name: "Breaking Homicide",
      origin_country: ["US"],
      original_language: "en",
      original_name: "Breaking Homicide",
      overview:
        "Former Rhode Island police Sgt. Derrick Levasseur and forensic psychologist Kris Mohandie answer the pleas of desperate families and investigate murder cases that have officially gone cold.",
      popularity: 0.751,
      poster_path: "/p6NMEDamsp6VpAC9vHem6kOsth8.jpg",
      vote_average: 6.3,
      vote_count: 3,
    },
    {
      backdrop_path: null,
      first_air_date: "2005-09-11",
      genre_ids: [],
      id: 10398,
      name: "Breaking Bonaduce",
      origin_country: ["US"],
      original_language: "en",
      original_name: "Breaking Bonaduce",
      overview:
        "Breaking Bonaduce was an American reality television series on VH1, focusing on former child-actor Danny Bonaduce, and how his increasingly unstable lifestyle impacted his then-wife, Gretchen, and their two children. The series premiered in September 2005 and ended in December 2006.",
      popularity: 0.693,
      poster_path: null,
      vote_average: 3,
      vote_count: 1,
    },
    {
      backdrop_path: "/e1OGESutD3wBRoHw3I280v6L5Ux.jpg",
      first_air_date: "2021-09-23",
      genre_ids: [80],
      id: 132158,
      name: "Bangkok Breaking",
      origin_country: ["TH"],
      original_language: "th",
      original_name: "มหานครเมืองลวง",
      overview:
        "The six-episode series is centered around the wild world of Bangkok's road rescue services and Wanchai who is newly arrived in Bangkok and must unravel a city-wide conspiracy alongside a young, upstart journalist.",
      popularity: 33.734,
      poster_path: "/nAru8tj4RXbLzDL3r89QoVyP6FY.jpg",
      vote_average: 7,
      vote_count: 49,
    },
    {
      backdrop_path: "/62uKAkIw04RGjKw9NPbErc8bAW7.jpg",
      first_air_date: "2018-06-15",
      genre_ids: [99],
      id: 80131,
      name: "Breaking Big",
      origin_country: ["US"],
      original_language: "en",
      original_name: "Breaking Big",
      overview:
        "Why and how did some of the world's most influential artists, innovators, athletes and leaders break big? Talented men and women recount their most difficult, dramatic and serendipitous turning points.",
      popularity: 0.632,
      poster_path: "/4Rg2nu48ApEhKDmV77xS4liI1zN.jpg",
      vote_average: 2,
      vote_count: 1,
    },
    {
      backdrop_path: null,
      genre_ids: [],
      id: 49759,
      name: "Breaking Up",
      origin_country: [],
      original_language: "en",
      original_name: "Breaking Up",
      overview: "",
      popularity: 0.6,
      poster_path: null,
      vote_average: 0,
      vote_count: 0,
    },
  ],
};
